# require superuser level permissions and docker running
sudo: required
services:
  - docker

# executed before tests run
before_install:
  - docker build -t damo78/docker-react -f Dockerfile.dev .

# command to run after build
# default npm run test woud hang because usually interactive
# -- --coverage exits back to command line
# if any exit code other than 0, Travis identifies test fail
script:
  - docker run damo78/docker-react npm run test -- --coverage