sudo: required
services:
  - docker

before_install:
  - docker build -t damo78/docker-react -f Dockerfile.dev .

script:
  - docker run damo78/docker-react npm run test -- --coverage

# deploy to AWS
deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-303995393799"
  bucket_path: "docker-react"
  on:
    branch: master

  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
